addons:
  postgresql: '9.3'
services:
- postgresql
language: ruby
cache: bundler
rvm:
- 2.3.1
before_script:
- psql -c 'create database looking4_test;' -U postgres
- cp config/database.yml.travis config/database.yml
script:
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rake
